# Generated by Django 4.1.1 on 2023-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_removeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='SOME STRING', max_length=25)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='RemoveUser',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
