# Generated by Django 4.1.1 on 2023-03-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
