# Generated by Django 4.1.1 on 2023-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('mood', models.CharField(max_length=15)),
                ('note', models.CharField(max_length=1000000)),
            ],
        ),
    ]
