# Generated by Django 4.1.1 on 2023-02-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_note_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
