# Generated by Django 4.1.1 on 2023-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_remove_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='need_cups',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='note',
            name='now_cups',
            field=models.IntegerField(default=0),
        ),
    ]
