# Generated by Django 4.1.1 on 2023-02-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_note_need_cups_note_now_cups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
