# Generated by Django 4.1.1 on 2023-02-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_alter_note_need_cups_alter_note_now_cups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='need_cups',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='now_cups',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
