# Generated by Django 4.1.1 on 2023-02-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_alter_note_need_cups_alter_note_now_cups'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cases_list',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
