# Generated by Django 4.1.1 on 2023-02-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_note_cases_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(blank=True, max_length=100000, null=True)),
                ('home', models.CharField(blank=True, max_length=100000, null=True)),
                ('development', models.CharField(blank=True, max_length=100000, null=True)),
                ('rest', models.CharField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='cases_list',
        ),
    ]
