# Generated by Django 4.1.1 on 2023-02-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_todolist_remove_note_cases_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
