# Generated by Django 4.1.1 on 2023-02-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_todolist_time_todolist_username_alter_note_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
