# Generated by Django 4.1.1 on 2023-02-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_alter_note_time_alter_todolist_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='time',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='time',
        ),
    ]
