# Generated by Django 4.1.1 on 2023-02-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_remove_note_time_remove_todolist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
