# Generated by Django 4.1.1 on 2023-02-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_note_time_todolist_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='time',
        ),
    ]
