# Generated by Django 4.1.1 on 2023-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_todolist_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='SOME STRING', max_length=25)),
                ('list_name', models.CharField(blank=True, max_length=25, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListsDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('case_name', models.CharField(default='SOME STRING', max_length=25)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListsHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('case_name', models.CharField(default='SOME STRING', max_length=25)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListsRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('case_name', models.CharField(default='SOME STRING', max_length=25)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListsWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('case_name', models.CharField(default='SOME STRING', max_length=25)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
