# Generated by Django 4.1.1 on 2023-02-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0018_lists_listsdevelopment_listshome_listsrest_listswork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
