# Generated by Django 4.1.1 on 2023-02-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_delete_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listsdevelopment',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
        migrations.AddField(
            model_name='listshome',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
        migrations.AddField(
            model_name='listsrest',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
        migrations.AddField(
            model_name='listswork',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
    ]
