# Generated by Django 4.1.1 on 2023-02-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_listsdevelopment_username_listshome_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listsdevelopment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='listshome',
            name='username',
        ),
        migrations.RemoveField(
            model_name='listsrest',
            name='username',
        ),
        migrations.RemoveField(
            model_name='listswork',
            name='username',
        ),
    ]
