# Generated by Django 4.1.1 on 2023-02-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0021_remove_listsdevelopment_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='SOME STRING', max_length=25)),
                ('goal_name', models.CharField(default='SOME STRING', max_length=25)),
                ('notification_time', models.CharField(default='SOME STRING', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GoalExec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
