# Generated by Django 4.1.1 on 2023-03-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0023_goalexec_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
