# Generated by Django 4.1.1 on 2023-04-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0025_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='notification_time',
        ),
        migrations.AddField(
            model_name='goal',
            name='notification_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='notification_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
