# Generated by Django 4.2.1 on 2023-05-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0027_remove_goalexec_note_id_alter_goalexec_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListsWork',
        ),
        migrations.AlterField(
            model_name='goalexec',
            name='time',
            field=models.CharField(default='2023-05-15', max_length=25),
        ),
    ]
