# Generated by Django 4.2.1 on 2023-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0028_delete_listswork_alter_goalexec_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListsWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('case_name', models.CharField(default='SOME STRING', max_length=25)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
